#!/usr/bin/env python3
"""Export YAML fixtures into synchronized JSON snapshots."""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from prophecycm.content import loaders

FIXTURE_ROOT = REPO_ROOT / "docs" / "data-model" / "fixtures"
GENERATED_ROOT = FIXTURE_ROOT / "generated"
HEADER_COMMENT = (
    "// Generated from YAML fixtures. Do not edit this file directly; "
    "update the YAML sources and rerun tools/export_yaml_fixtures_to_json.py.\n"
)


def load_fixture(stem: str) -> object:
    path = loaders._resolve_content_file(FIXTURE_ROOT, stem)
    return loaders._load_payload(path)


def export_fixture(stem: str) -> Path:
    payload = load_fixture(stem)
    GENERATED_ROOT.mkdir(parents=True, exist_ok=True)
    output_path = GENERATED_ROOT / f"{stem}.json"
    with output_path.open("w", encoding="utf-8") as fh:
        fh.write(HEADER_COMMENT)
        json.dump(payload, fh, ensure_ascii=False, indent=2)
        fh.write("\n")
    return output_path


def main() -> None:
    for stem in ("items", "locations", "npcs", "start_menu"):
        output_path = export_fixture(stem)
        print(f"Wrote {output_path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
